### PR TITLE
Publish artifacts

### PR DESCRIPTION
**Pull request by jgustie**
See issue #24.

This PR:
1. Upgrades Gradle from 2.10 to 2.14
2. Changes the group ID (duplicates #30)
3. Adds a Maven publication we can send to JFrog
4. Publishes coverage to Coveralls
5. Publishes to either Bintray or OSS JFrog on every CI build

In order to perform a release, you just update the project version to drop the snapshot and tag the commit. Push it (real good). Increment the version, adding the snapshot back, and push that after the Travis build completes successfully.

### CODE REVIEW

**Comment by mydimension** [comment]
any reason you removed the additional jdk travis builds? (and the `before_cache` directive?)

```
jdk:
    - oraclejdk8
    - oraclejdk7
    - openjdk7
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
```

**Comment by jgustie** [comment]
Honestly I just took what I had done in BDIO which only had the single JDK. I'm not convinced we need the extra jobs run, but I'll stick them back in. Also, I double checked the Travis documentation on the module lock file and it looks like they even recommend wiping out more then just that file. I'll update that to the latest as well.

**Comment by jgustie** [comment]
Once this is merged, you can get Ohcount4j releases from `http://dl.bintray.com/bds/oss` and snapshots from `https://oss.jfrog.org/artifactory/oss-snapshot-local`.

**Comment by mydimension** [comment]
@blackducksoftware/ohcount4j-fab-five : go-nogo to merge?

**Pull request merged**
